# Generated by Django 4.1.1 on 2022-09-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('event_admin', models.IntegerField()),
                ('approved_users', models.JSONField()),
                ('pending_users', models.JSONField()),
                ('start_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('bicycle', 'bicycle'), ('hiking', 'hiking')], default='hiking', max_length=50)),
                ('departure', models.IntegerField()),
                ('stopping', models.JSONField()),
                ('destination', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
