# Generated by Django 4.1.1 on 2022-09-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'route', 'verbose_name_plural': 'route'},
        ),
    ]
