# Generated by Django 4.1.1 on 2022-10-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_review_route_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='info',
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
