# Generated by Django 4.1.1 on 2022-10-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_remove_event_route_id_remove_place_info_event_route_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
